name: ci
on:
  pull_request:
  push:
    branches:
    - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-go@v2
      with:
        go-version: '1.17'
    - name: run unit tests
      run: go test ./... -race
